@echo off
set /p PGPASSWORD=<Password.txt
set dbName= SenioCare_DB
set /p execPath=<PostgresPath.txt
echo Creating Database %dbname%
%execPath% --no-psqlrc --quiet -h localhost -U postgres -f DropDB.sql
%execPath% --no-psqlrc --quiet -h localhost -U postgres -f CreateDBInitial.sql

echo Creating Table Person...
%execPath% --no-psqlrc --quiet -h localhost -U postgres -d %dbName% -f CreatePersonTable.sql
echo Creating Table Employee...
%execPath% --no-psqlrc --quiet -h localhost -U postgres -d %dbName% -f CreateEmployeeTable.sql
echo Creating Table Client...
%execPath% --no-psqlrc --quiet -h localhost -U postgres -d %dbName% -f CreateClientTable.sql
echo Creating Table Request...
%execPath% --no-psqlrc --quiet -h localhost -U postgres -d %dbName% -f CreateRequestTable.sql
echo Creating Table EmployeePay
%execPath% --no-psqlrc --quiet -h localhost -U postgres -d %dbName% -f CreateEmployeePayTable.sql
echo Creating Table Category...
%execPath% --no-psqlrc --quiet -h localhost -U postgres -d %dbName% -f CreateCategoryTable.sql
echo Inserting into Category table...
%execPath% --no-psqlrc --quiet -h localhost -U postgres -d %dbName% -f InsertintoCategory.sql
echo Creating structured data...
java PersonDataGen
echo Inserting into Person table...
%execPath%  -h localhost -U postgres -d %dbName% -f InsertintoPerson.sql
echo Inserting into Employee table...
%execPath% --no-psqlrc --quiet -h localhost -U postgres -d %dbName% -f InsertintoEmployee.sql
echo Inserting into Client table...
%execPath% --no-psqlrc --quiet -h localhost -U postgres -d %dbName% -f InsertintoClient.sql
echo Inserting into EmployeePay table...
%execPath% --no-psqlrc --quiet -h localhost -U postgres -d %dbName% -f InsertintoEmployeePay.sql
echo Inserting into Request table...
%execPath% --no-psqlrc --quiet -h localhost -U postgres -d %dbName% -f InsertintoRequest.sql
pause